// flow-typed signature: 959f93ccc97dbe27c4c82a73bee6a67a
// flow-typed version: <<STUB>>/engine-fork_v3.0.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'engine-fork'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'engine-fork' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'engine-fork/anime' {
  declare module.exports: any;
}

declare module 'engine-fork/anime.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'engine-fork/anime.js' {
  declare module.exports: $Exports<'engine-fork/anime'>;
}
declare module 'engine-fork/anime.min.js' {
  declare module.exports: $Exports<'engine-fork/anime.min'>;
}
