// flow-typed signature: dcc605496252a35bd9095de50b55c953
// flow-typed version: <<STUB>>/fastdom_v1.0.8/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastdom/extensions/fastdom-promised' {
  declare module.exports: any;
}

declare module 'fastdom/extensions/fastdom-sandbox' {
  declare module.exports: any;
}

declare module 'fastdom/fastdom-strict' {
  declare module.exports: any;
}

declare module 'fastdom/fastdom' {
  declare module.exports: any;
}

declare module 'fastdom/fastdom.min' {
  declare module.exports: any;
}

declare module 'fastdom/src/fastdom-strict' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastdom/extensions/fastdom-promised.js' {
  declare module.exports: $Exports<'fastdom/extensions/fastdom-promised'>;
}
declare module 'fastdom/extensions/fastdom-sandbox.js' {
  declare module.exports: $Exports<'fastdom/extensions/fastdom-sandbox'>;
}
declare module 'fastdom/fastdom-strict.js' {
  declare module.exports: $Exports<'fastdom/fastdom-strict'>;
}
declare module 'fastdom/fastdom.js' {
  declare module.exports: $Exports<'fastdom/fastdom'>;
}
declare module 'fastdom/fastdom.min.js' {
  declare module.exports: $Exports<'fastdom/fastdom.min'>;
}
declare module 'fastdom/src/fastdom-strict.js' {
  declare module.exports: $Exports<'fastdom/src/fastdom-strict'>;
}
