// flow-typed signature: 0cdd208c23ed98da0d92478e18c1c0ad
// flow-typed version: <<STUB>>/rebound_v0.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rebound'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rebound' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rebound/__tests__/reboundSpec' {
  declare module.exports: any;
}

declare module 'rebound/dist/rebound' {
  declare module.exports: any;
}

declare module 'rebound/rollup.config' {
  declare module.exports: any;
}

declare module 'rebound/src/BouncyConversion' {
  declare module.exports: any;
}

declare module 'rebound/src/Loopers' {
  declare module.exports: any;
}

declare module 'rebound/src/MathUtil' {
  declare module.exports: any;
}

declare module 'rebound/src/OrigamiValueConverter' {
  declare module.exports: any;
}

declare module 'rebound/src/PhysicsState' {
  declare module.exports: any;
}

declare module 'rebound/src/Spring' {
  declare module.exports: any;
}

declare module 'rebound/src/SpringConfig' {
  declare module.exports: any;
}

declare module 'rebound/src/SpringSystem' {
  declare module.exports: any;
}

declare module 'rebound/src/index' {
  declare module.exports: any;
}

declare module 'rebound/src/onFrame' {
  declare module.exports: any;
}

declare module 'rebound/src/types' {
  declare module.exports: any;
}

declare module 'rebound/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rebound/__tests__/reboundSpec.js' {
  declare module.exports: $Exports<'rebound/__tests__/reboundSpec'>;
}
declare module 'rebound/dist/rebound.js' {
  declare module.exports: $Exports<'rebound/dist/rebound'>;
}
declare module 'rebound/rollup.config.js' {
  declare module.exports: $Exports<'rebound/rollup.config'>;
}
declare module 'rebound/src/BouncyConversion.js' {
  declare module.exports: $Exports<'rebound/src/BouncyConversion'>;
}
declare module 'rebound/src/Loopers.js' {
  declare module.exports: $Exports<'rebound/src/Loopers'>;
}
declare module 'rebound/src/MathUtil.js' {
  declare module.exports: $Exports<'rebound/src/MathUtil'>;
}
declare module 'rebound/src/OrigamiValueConverter.js' {
  declare module.exports: $Exports<'rebound/src/OrigamiValueConverter'>;
}
declare module 'rebound/src/PhysicsState.js' {
  declare module.exports: $Exports<'rebound/src/PhysicsState'>;
}
declare module 'rebound/src/Spring.js' {
  declare module.exports: $Exports<'rebound/src/Spring'>;
}
declare module 'rebound/src/SpringConfig.js' {
  declare module.exports: $Exports<'rebound/src/SpringConfig'>;
}
declare module 'rebound/src/SpringSystem.js' {
  declare module.exports: $Exports<'rebound/src/SpringSystem'>;
}
declare module 'rebound/src/index.js' {
  declare module.exports: $Exports<'rebound/src/index'>;
}
declare module 'rebound/src/onFrame.js' {
  declare module.exports: $Exports<'rebound/src/onFrame'>;
}
declare module 'rebound/src/types.js' {
  declare module.exports: $Exports<'rebound/src/types'>;
}
declare module 'rebound/src/util.js' {
  declare module.exports: $Exports<'rebound/src/util'>;
}
