// flow-typed signature: 90b0985e8e929df0f0d9618cdd35e520
// flow-typed version: <<STUB>>/svg-tag-names_v1.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-tag-names'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-tag-names' {
  declare module.exports: any;
}
